spring.application.name=gestor-guias
server.port=8080

# Desactivar S3 para pruebas locales (IMPORTANTE)
spring.autoconfigure.exclude=io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration

# ===== CONFIGURACIÓN H2 (pruebas locales) =====
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# ===== CONFIGURACIÓN RABBITMQ =====
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===== AWS S3 =====
aws.s3.bucket-name=guias-despacho-grupo2
aws.region=us-east-1
aws.s3.region=us-east-1

# ===== EFS =====
efs.mount.path=/mnt/efs

# ===== AZURE AD B2C (OAuth2) =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/0a871409-07d4-49ac-b239-899c125b9820/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=84db7c63-dcd4-4741-9a3c-12bca720c910

